let database = require('../app_methods/database');

function Book(name, author, totalQuantity) {
  this.name = name;
  this.author = author;
  this.totalQuantity = totalQuantity;
  // the book Id will be autogenerated and will increment based on the Id of the most recent book in the database
  this.bookId = database.books.length ? database.books[database.books.length - 1].booksId + 1 : 1;
  this.borrowers = [];
  this.quantityAvailable = this.totalQuantity - this.borrowers.length;
  database.books.push(this);
}

Book.createBook = function (name, author, totalQuantity) {
  return new Book(name, author, totalQuantity);
}

Book.searchBook = function (name) {
  let booksWithName = [];
  for (let index = 0; index < database.books.length; index++) {
    if (database.books[index].name === name) {
      booksWithName.push({ name: database.books[index].name, author: database.books[index].author });
    }
  }
  return booksWithName;
}

Book.updateBook = function (Id, updateDetails) {

}

Book.deleteBook = function (bookId) {

}

Book.readBook = function () {

}

Book.readAllBooks = function () {

}
module.exports = Book;