let database = require('../app_methods/database');

function Book(name, author, totalQuantity) {
  this.name = name;
  this.author = author;
  this.totalQuantity = totalQuantity;
  // the book Id will be autogenerated and will increment based on the Id of the most recent book in the database
  this.bookId = database.books.length ? database.books[database.books.length - 1].booksId + 1 : 1;
  this.borrowers = [];
  this.quantityAvailable = this.totalQuantity - this.borrowers.length;
  database.books.push(this);
}

Book.createBook = function (name, author, totalQuantity) {
  return new Book(name, author, totalQuantity);
}

Book.searchBook = function (name) {
  let booksWithName = [];
  for (let index = 0; index < database.books.length; index++) {
    if (database.books[index].name === name) {
      let bookName = database.books[index].name;
      let bookAuthor = database.books[index].author;
      booksWithName.push({ name: bookName, author: bookAuthor });
    }
  }
  if (booksWithName.length) return booksWithName;
  return 'Invalid id';
}

Book.updateBook = function (bookId, updateDetails) {
  for (let index = 0; index < database.books.length; index++) {
    if (database.books[index].bookId === bookId) {
      return database.books[index].totalQuantity = updateDetails.totalQuantity;
    }
  }
  return 'Invalid id';
}

Book.deleteBook = function (bookId) {

}

Book.readABook = function (bookId) {
  for (let index = 0; index < database.books.length; index++) {
    if (database.books[index].bookId === bookId) {
      return database.books[index];
    }
  }
  return 'Invalid id';
}

Book.readAllBooks = function () {
  return database.books;
}
module.exports = Book;