var database = require('../app_methods/database');
var Book = require('../app_methods/book');

// user constructor function
function User(name, email) {
  this.name = name;
  this.email = email;
  // the user Id will be autogenerated and will increment based on the Id of the most recent user in the database
  this.userId = database.users.length ? database.users[database.users.length - 1].usersId + 1 : 1;
}
User.prototype.save = function () {
  database.users.push(this);
};

// User searches for a book by name
User.prototype.searchBook = function (name) {
  return Book.searchBook(name);
}

module.exports = User;